name: deploy
on:
  workflow_run:
    workflows: ["Pylint", "pytest"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: remote-ssh
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 3.34.193.26
          username: ec2-user
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd learn-github-actions
            git pull origin main
            flask --app app run --host 0.0.0.0 &
